name: CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  test-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-mock
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test with pytest
        run: |
          pytest

      - name: Get latest tag
        id: get_latest_tag
        run: |
          git fetch --tags
          latest_tag=$(git tag -l --sort=-v:refname "v*" | head -n 1 || echo "v0.0.0")
          echo "Latest tag: $latest_tag"
          echo "LATEST_TAG=$latest_tag" >> "$GITHUB_ENV"

      - name: Bump version
        id: bump_version
        run: |
          latest_version=${LATEST_TAG#v}
          IFS='.' read -r major minor patch <<< "$latest_version"
          new_version="v$major.$minor.$((patch + 1))"
          echo "NEW_VERSION=$new_version" >> "$GITHUB_ENV"
          echo "New version will be: $new_version"

      - name: Check if tag exists
        id: check_tag
        run: |
          if git tag -l | grep -q "^${{ env.NEW_VERSION }}$"; then
            echo "Warning: Tag ${{ env.NEW_VERSION }} already exists"
            # Increment patch version again if tag exists
            latest_version=${NEW_VERSION#v}
            IFS='.' read -r major minor patch <<< "$latest_version"
            new_version="v$major.$minor.$((patch + 1))"
            echo "Using incremented version: $new_version"
            echo "NEW_VERSION=$new_version" >> "$GITHUB_ENV"
          fi

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.NEW_VERSION }}
          release_name: Release ${{ env.NEW_VERSION }}
          body: |
            Automated release for changes in main branch
            
            Changes in this release:
            ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            laffin/cloudproxy:latest
            laffin/cloudproxy:${{ env.NEW_VERSION }}

      # PyPI Publishing Steps
      - name: Update version in pyproject.toml
        run: |
          # Strip the 'v' prefix from the version
          VERSION=${NEW_VERSION#v}
          # Use sed to update the version in pyproject.toml to match the release
          sed -i "s/version = \"[0-9]*\.[0-9]*\.[0-9]*\"/version = \"$VERSION\"/" pyproject.toml
          cat pyproject.toml | grep version

      - name: Install PyPI publishing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build and publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m build
          twine check dist/*
          twine upload dist/*
